### ISSUE TITLE
Use with Angular Universal (platform-server)

### ISSUE THREAD

**Issue by MartinNuc** [Nolanus/ngx-page-scroll#212] opened 2017-08-13 10:46 UTC
I am trying server side rendering with angular-cli according to https://github.com/angular/angular-cli/wiki/stories-universal-rendering

First I got error:

```
...../node_modules/@angular/core/bundles/core.umd.js:382
            throw 'reflect-metadata shim is required when using class decorators';
```

Therefore I added to my `main.server.ts`:

```
import 'reflect-metadata';
export { AppServerModule } from './app/app.server.module';
```

which lead me to this error:

```
....../node_modules/ng2-page-scroll/src/ng2-page-scroll.service.js:1
(function (exports, require, module, __filename, __dirname) { import { Injectable, Optional, SkipSelf, isDevMode } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.wUSp (......../dist-server/main.438b99fa912aa294afda.bundle.js:1:216619)
```

I guess problem is that ng2-page-scroll uses ES2015 module format which is not usable in node environment.

After some googling I found this issue: https://github.com/angular/angular-cli/issues/7200 which confirmed my thoughts.

If others encounter this issue you can use https://gist.github.com/J2D2Development/6f520dd991a6a33c1152aabcdf346790 mentioned in that thread. It worked for me on `ng2-page-scroll` but I got stucked on the next library.

Not sure what is a correct solution to this problem.

**Comment by mcferren** [comment] 2017-09-01 03:47
updating to   "@ngrx/effects": "^4.0.5" and "@ngrx/store": "^4.0.3" solved the issue for me

**Comment by MartinNuc** [comment] 2017-09-01 08:23
@mcferren which libs?

**Comment by mcferren** [comment] 2017-09-01 12:58
@ngrx/effects: ^4.0.5,
@ngrx/store: ^4.0.3

**Comment by MartinNuc** [comment] 2017-09-01 13:40
I dont use these libs. This is probably bug in cli. Someone wrote it helps to move built files to the root dir of lib.

**Comment by ysus** [comment] 2017-09-02 03:49
i use this repo 
[https://github.com/FrozenPandaz/ng-universal-demo](https://github.com/FrozenPandaz/ng-universal-demo)
with this libs updates and works perfect :
![package](https://user-images.githubusercontent.com/14302557/29992708-ca497ef6-8f67-11e7-867e-e89a50a47af7.png)

**Comment by msio777** [comment] 2017-09-15 11:56
[this](https://gist.github.com/J2D2Development/6f520dd991a6a33c1152aabcdf346790) works but with little modification
```
const data = fs.readFileSync(join(__dirname, '/dist/dist-server/main.bundle.js'), 'utf-8');
const ssrPageScrollBundle = 'require("ng2-page-scroll/bundles/ng2-page-scroll.umd.js")';
const newCode = data.replace('require("ng2-page-scroll")', ssrPageScrollBundle)
  .replace('require("ng2-page-scroll/src/ng2-page-scroll.module")', ssrPageScrollBundle)
  .replace('require("ng2-page-scroll/src/ng2-page-scroll.service")', ssrPageScrollBundle)
  .replace('require("ng2-page-scroll/src/ng2-page-scroll.directive")', ssrPageScrollBundle)

fs.writeFileSync('./dist/dist-server/main.bundle.js', newCode, 'utf-8');
console.log('Done editing main.bundle.js to use amd bundles for external libraries');
```

I had to use sync read file and search for  whole require string

**Comment by rsnider19** [comment] 2017-10-05 00:44
I would love for a better resolution to this issue other than @msio777 's hack.

**Comment by Nolanus** [comment] 2017-10-05 21:44
@rsnider19 Feel free to provide a PR or suggest changes, I'm currently not working with any angular university setup

**Comment by andrebnf** [comment] 2018-05-18 21:15
This bug does not happen on version `4.0.0-beta.12`

**Comment by Ks89** [comment] 2018-07-22 19:07
@Nolanus In my opinion the problem is not related to the library itself, but it's about your build system with rollup.
In your package.json (of the library downloaded from npmjs) there aren't some keys like: es2015, metadata.
To be sure that your library will work with everyone you should follow the official specifications by the angular team: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx

To support these specifications, you should use [ng-packagr](https://github.com/dherges/ng-packagr) or [the official library support in angular-cli](https://github.com/angular/angular-cli/wiki/stories-create-library).
I suggest to use angular-cli (inside it uses ng-packagr) because supported by the angular team.

I created a library with ng-packagr and all build /support problems disappeared when I switched to ng-packagr months and months ago: [@ks89/angular-modal-gallery](https://github.com/Ks89/angular-modal-gallery)
The latest stable version of my library is using ng-packagr and it's working very well, but from the next major release (WIP) I'll switch to angular-cli, because I made some experiments and It's simpler to setup and it's working very well.
I found this issue in the official doc website of my library, because I'm using your library.

If you want I can help you, but the problem is that a pull request will be a full refactoring (because you must follow best practices of angular-cli and put all your code in specific folders and so on) and it will also broke your TravisCI setup.
My suggestion is to create a new empty project with angular-cli library and add all your stuff step by step starting from the code to your tests.

**Comment by Nolanus** [comment] 2019-01-24 15:40
Closing this, as new v6 of ngx-page-scroll uses angular-cli library features and now all necessary package.json fields and bundle files should be included. Please comment in case there are still issues.

**Closed by Nolanus** 2019-01-24 15:40 UTC
Labels: help wanted
